<?php
/**
 *
 * Copyright 2017 Simnang, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */

namespace Simnang\LoanPro\Utils\Parser;


class ExpressionTreeNode implements \JsonSerializable {
    public $token = null;
    public $leftNode = null;
    public $rightNode = null;
    public $parentNode = null;

    public function __construct($val){
        $this->token = $val;
    }

    public function AddLeftChildNode(ExpressionTreeNode $node){
        if(is_null($this->leftNode)) {
            $this->leftNode = $node;
            $node->parentNode = $this;
        }
    }

    public function AddRightChildNode(ExpressionTreeNode $node){
        if(is_null($this->rightNode)) {
            $this->rightNode = $node;
            $node->parentNode = $this;
        }
    }

    public function AddNextChildNode(ExpressionTreeNode $node){
        if(is_null($this->leftNode)) {
            $this->leftNode = $node;
            $node->parentNode = $this;
        }
        else if(is_null($this->rightNode)) {
            $this->rightNode = $node;
            $node->parentNode = $this;
        }
    }

    public function HasBothChildren(){
        return !$this->MissingLeftChild() && !$this->MissingRightChild();
    }

    public function MissingLeftChild(){
        return is_null($this->leftNode);
    }

    public function MissingRightChild(){
        return is_null($this->rightNode);
    }

    public function HasParent(){
        return !is_null($this->parentNode);
    }

    /**
     * Specify data which should be serialized to JSON
     *
     * @link  http://php.net/manual/en/jsonserializable.jsonserialize.php
     * @return mixed data which can be serialized by <b>json_encode</b>,
     *        which is a value of any type other than a resource.
     * @since 5.4.0
     */
    function jsonSerialize()
    {
        return ['token'=>$this->token, 'left'=>$this->leftNode, 'right'=>$this->rightNode];
    }
}

class SingleChildExpressionTreeNode extends ExpressionTreeNode{


    public function __construct($val)
    {
        parent::__construct($val); // TODO: Change the autogenerated stub
    }

    public function AddLeftChildNode(ExpressionTreeNode $node)
    {
        parent::AddLeftChildNode($node); // TODO: Change the autogenerated stub
    }

    public function AddRightChildNode(ExpressionTreeNode $node)
    {
        throw new \OutOfBoundsException("Single child nodes only have one child, cannot access second child");
    }

    public function AddNextChildNode(ExpressionTreeNode $node)
    {
        parent::AddLeftChildNode($node); // TODO: Change the autogenerated stub
    }

    public function HasBothChildren()
    {
        return !parent::MissingLeftChild(); // TODO: Change the autogenerated stub
    }

    public function MissingLeftChild()
    {
        return parent::MissingLeftChild(); // TODO: Change the autogenerated stub
    }

    public function MissingRightChild()
    {
        return false;
    }

    public function HasParent()
    {
        return parent::HasParent(); // TODO: Change the autogenerated stub
    }

    /**
     * Specify data which should be serialized to JSON
     *
     * @link  http://php.net/manual/en/jsonserializable.jsonserialize.php
     * @return mixed data which can be serialized by <b>json_encode</b>,
     *        which is a value of any type other than a resource.
     * @since 5.4.0
     */
    function jsonSerialize()
    {
        return ['token'=>$this->token, 'left'=>$this->leftNode];
    }
}
